schema_version: 1

context:
  name: jsonpath-ng
  version: "1.9.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 39f6b5bdbf3f70ae02ea58a2a6d3631415f6655894bb1f40514a0de8486e5976

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install --no-deps . -vv
  python:
    entry_points:
      - jsonpath_ng=jsonpath_ng.bin.jsonpath:entry_point

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - ply

tests:
  - python:
      imports:
        - jsonpath_ng
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - jsonpath_ng --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python JSONPath Next-Generation
  description: |
    A final implementation of JSONPath for Python that aims to be standard compliant,
    including arithmetic and binary comparison operators.
  homepage: https://github.com/h2non/jsonpath-ng
  repository: https://github.com/h2non/jsonpath-ng

extra:
  recipe-maintainers:
    - shcheklein
    - thewchan
